use crate::{Coins, Enemy, Environment as E, Layer as L, Rarity::*};

pub fn list_enemies() -> Box<[Enemy]> {
    Box::new([
        Enemy::new(
            1,
            "Blue Slime",
            25,
            2,
            Coins::new(0, 0, 25),
            vec![E::Forest, E::Any],
            vec![L::Surface, L::Underground],
            Common,
        ),
        Enemy::new(
            2,
            "Demon Eye",
            60,
            2,
            Coins::new(0, 0, 75),
            vec![E::Any, E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            3,
            "Zombie",
            45,
            6,
            Coins::new(0, 0, 60),
            vec![E::Any, E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            6,
            "Eater of Souls",
            40,
            8,
            Coins::new(0, 0, 90),
            vec![E::Corruption],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            7,
            "Devourer",
            100,
            6,
            Coins::new(0, 1, 40),
            vec![E::Corruption],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            16,
            "Mother Slime",
            90,
            7,
            Coins::new(0, 0, 75),
            vec![E::Any],
            vec![L::Caverns],
            Common,
        ),
        Enemy::new(
            24,
            "Fire Imp",
            70,
            16,
            Coins::new(0, 3, 50),
            vec![E::Any],
            vec![L::Underworld],
            Common,
        ),
        Enemy::new(
            26,
            "Goblin Peon",
            60,
            4,
            Coins::new(0, 1, 0),
            vec![E::Event, E::Goblin],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            27,
            "Goblin Thief",
            80,
            6,
            Coins::new(0, 2, 0),
            vec![E::Event, E::Goblin],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            28,
            "Goblin Warrior",
            110,
            8,
            Coins::new(0, 1, 50),
            vec![E::Event, E::Goblin],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            29,
            "Goblin Sorcerer",
            40,
            2,
            Coins::new(0, 2, 0),
            vec![E::Event, E::Goblin],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            31,
            "Angry Bones",
            80,
            8,
            Coins::new(0, 1, 30),
            vec![E::Dungeon],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            32,
            "Dark Caster",
            50,
            2,
            Coins::new(0, 1, 40),
            vec![E::Dungeon],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            34,
            "Cursed Skull",
            40,
            6,
            Coins::new(0, 1, 50),
            vec![E::Dungeon],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            39,
            "Bone Serpent",
            300,
            18,
            Coins::new(0, 12, 0),
            vec![E::Any],
            vec![L::Underworld],
            Uncommon,
        ),
        Enemy::new(
            42,
            "Hornet",
            48,
            12,
            Coins::new(0, 2, 0),
            vec![E::Jungle],
            vec![L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            43,
            "Man Eater",
            110,
            10,
            Coins::new(0, 3, 50),
            vec![E::Jungle],
            vec![L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            44,
            "Undead Miner",
            70,
            9,
            Coins::new(0, 2, 50),
            vec![E::Any],
            vec![L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            45,
            "Tim",
            200,
            4,
            Coins::new(0, 50, 0),
            vec![E::Any],
            vec![L::Caverns],
            Rare,
        ),
        Enemy::new(
            46,
            "Bunny",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Forest],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            47,
            "Corrupt Bunny",
            70,
            4,
            Coins::new(0, 5, 0),
            vec![E::Event, E::Night],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            48,
            "Harpy",
            100,
            8,
            Coins::new(0, 3, 0),
            vec![E::Any],
            vec![L::Space],
            Common,
        ),
        Enemy::new(
            49,
            "Cave Bat",
            16,
            2,
            Coins::new(0, 0, 90),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            51,
            "Jungle Bat",
            34,
            4,
            Coins::new(0, 0, 80),
            vec![E::Jungle],
            vec![L::Surface, L::Underground],
            Common,
        ),
        Enemy::new(
            52,
            "Doctor Bones",
            500,
            100,
            Coins::new(0, 10, 0),
            vec![E::Jungle],
            vec![L::Surface, L::Underground],
            Rare,
        ),
        Enemy::new(
            53,
            "The Groom",
            200,
            8,
            Coins::new(0, 10, 0),
            vec![E::Event, E::Blood, E::Graveyard],
            vec![L::Surface],
            Rare,
        ),
        Enemy::new(
            55,
            "Goldfish",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            56,
            "Snatcher",
            60,
            10,
            Coins::new(0, 0, 90),
            vec![E::Jungle],
            vec![L::Surface, L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            57,
            "Corrupt Goldfish",
            100,
            6,
            Coins::new(0, 5, 0),
            vec![E::Corruption, E::Blood, E::Event],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            58,
            "Piranha",
            30,
            2,
            Coins::new(0, 0, 50),
            vec![E::Jungle],
            vec![L::Surface, L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            59,
            "Lava Slime",
            50,
            10,
            Coins::new(0, 1, 20),
            vec![E::Any],
            vec![L::Underworld],
            Common,
        ),
        Enemy::new(
            60,
            "Hellbat",
            46,
            8,
            Coins::new(0, 1, 20),
            vec![E::Any],
            vec![L::Underworld],
            Common,
        ),
        Enemy::new(
            61,
            "Vulture",
            40,
            4,
            Coins::new(0, 0, 60),
            vec![E::Desert],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            62,
            "Demon",
            120,
            8,
            Coins::new(0, 3, 0),
            vec![E::Any],
            vec![L::Underworld],
            Common,
        ),
        Enemy::new(
            63,
            "Blue Jellyfish",
            34,
            4,
            Coins::new(0, 1, 0),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            64,
            "Pink Jellyfish",
            70,
            4,
            Coins::new(0, 1, 0),
            vec![E::Ocean],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            65,
            "Shark",
            300,
            2,
            Coins::new(0, 4, 0),
            vec![E::Ocean],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            66,
            "Voodoo Demon",
            140,
            8,
            Coins::new(0, 10, 0),
            vec![E::Any],
            vec![L::Underworld],
            Uncommon,
        ),
        Enemy::new(
            67,
            "Crab",
            40,
            10,
            Coins::new(0, 0, 60),
            vec![E::Ocean],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            69,
            "Antlion",
            45,
            6,
            Coins::new(0, 0, 60),
            vec![E::Desert],
            vec![L::Surface, L::Underground],
            Common,
        ),
        Enemy::new(
            71,
            "Dungeon Slime",
            150,
            7,
            Coins::new(0, 1, 50),
            vec![E::Dungeon],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            73,
            "Goblin Scout",
            80,
            6,
            Coins::new(0, 2, 0),
            vec![E::Forest],
            vec![L::Surface],
            Rare,
        ),
        Enemy::new(
            74,
            "Bird",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Forest, E::Snow, E::Hallow],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            75,
            "Pixie",
            150,
            20,
            Coins::new(0, 3, 50),
            vec![E::Hallow],
            vec![L::Surface, L::Underground],
            Common,
        ),
        Enemy::new(
            77,
            "Armored Skeleton",
            260,
            28,
            Coins::new(0, 4, 0),
            vec![E::Any],
            vec![L::Caverns],
            Common,
        ),
        Enemy::new(
            78,
            "Mummy",
            130,
            16,
            Coins::new(0, 6, 0),
            vec![E::Desert],
            vec![L::Surface, L::Underground],
            Common,
        ),
        Enemy::new(
            79,
            "Dark Mummy",
            180,
            18,
            Coins::new(0, 7, 0),
            vec![E::Desert, E::Corruption],
            vec![L::Surface, L::Underground],
            Common,
        ),
        Enemy::new(
            80,
            "Light Mummy",
            200,
            18,
            Coins::new(0, 7, 0),
            vec![E::Desert, E::Hallow],
            vec![L::Surface, L::Underground],
            Common,
        ),
        Enemy::new(
            81,
            "Corrupt Slime",
            170,
            20,
            Coins::new(0, 4, 0),
            vec![E::Corruption],
            vec![L::Surface, L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            82,
            "Wraith",
            160,
            16,
            Coins::new(0, 5, 0),
            vec![E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            83,
            "Cursed Hammer",
            200,
            18,
            Coins::new(0, 10, 0),
            vec![E::Corruption],
            vec![L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            84,
            "Enchanted Sword",
            200,
            18,
            Coins::new(0, 10, 0),
            vec![E::Hallow],
            vec![L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            85,
            "Mimic",
            500,
            30,
            Coins::new(10, 0, 0),
            vec![E::Any],
            vec![L::Any],
            Rare,
        ),
        Enemy::new(
            86,
            "Unicorn",
            400,
            30,
            Coins::new(0, 10, 0),
            vec![E::Hallow],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            87,
            "Wyvern",
            4000,
            20,
            Coins::new(1, 0, 0),
            vec![E::Any],
            vec![L::Space],
            Uncommon,
        ),
        Enemy::new(
            93,
            "Giant Bat",
            100,
            16,
            Coins::new(0, 4, 0),
            vec![E::Any],
            vec![L::Caverns],
            Common,
        ),
        Enemy::new(
            94,
            "Corruptor",
            230,
            32,
            Coins::new(0, 5, 0),
            vec![E::Corruption],
            vec![L::Surface, L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            95,
            "Digger",
            200,
            20,
            Coins::new(0, 3, 0),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            98,
            "World Feeder",
            500,
            40,
            Coins::new(0, 7, 0),
            vec![E::Corruption],
            vec![L::Surface, L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            101,
            "Clinger",
            320,
            30,
            Coins::new(0, 6, 0),
            vec![E::Corruption],
            vec![L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            102,
            "Angler Fish",
            90,
            22,
            Coins::new(0, 5, 0),
            vec![E::Any, E::Jungle],
            vec![L::Surface, L::Underground],
            Uncommon,
        ),
        Enemy::new(
            103,
            "Green Jellyfish",
            120,
            30,
            Coins::new(0, 8, 0),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            104,
            "Werewolf",
            350,
            38,
            Coins::new(0, 10, 0),
            vec![E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            109,
            "Clown",
            800,
            25,
            Coins::new(1, 0, 0),
            vec![E::Night, E::Event],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            110,
            "Skeleton Archer",
            210,
            14,
            Coins::new(0, 4, 0),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            111,
            "Goblin Archer",
            80,
            6,
            Coins::new(0, 2, 0),
            vec![E::Event],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            120,
            "Chaos Elemental",
            370,
            30,
            Coins::new(0, 6, 0),
            vec![E::Hallow],
            vec![L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            121,
            "Slimer",
            60,
            20,
            Coins::new(0, 1, 0),
            vec![E::Corruption],
            vec![L::Surface, L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            122,
            "Gastropod",
            220,
            22,
            Coins::new(0, 6, 0),
            vec![E::Hallow, E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            133,
            "Wandering Eye",
            300,
            20,
            Coins::new(0, 5, 0),
            vec![E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            137,
            "Illuminant Bat",
            200,
            30,
            Coins::new(0, 5, 0),
            vec![E::Hallow],
            vec![L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            138,
            "Illuminant Slime",
            180,
            30,
            Coins::new(0, 4, 0),
            vec![E::Hallow],
            vec![L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            140,
            "Posessed Armor",
            260,
            28,
            Coins::new(0, 4, 0),
            vec![E::Any, E::Night],
            vec![L::Surface, L::Underground],
            Common,
        ),
        Enemy::new(
            141,
            "Toxic Sludge",
            150,
            18,
            Coins::new(0, 4, 0),
            vec![E::Any],
            vec![L::Underground],
            Uncommon,
        ),
        Enemy::new(
            143,
            "Snowman Gangsta",
            200,
            20,
            Coins::new(0, 4, 0),
            vec![E::Event, E::Legion],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            144,
            "Mister Stabby",
            240,
            26,
            Coins::new(0, 4, 0),
            vec![E::Event, E::Legion],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            145,
            "Snow Balla",
            220,
            22,
            Coins::new(0, 4, 0),
            vec![E::Event, E::Legion],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            147,
            "Ice Slime",
            30,
            4,
            Coins::new(0, 0, 50),
            vec![E::Snow, E::Day],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            148,
            "Penguin",
            50,
            0,
            Coins::new(0, 0, 0),
            vec![E::Snow],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            150,
            "Ice Bat",
            30,
            6,
            Coins::new(0, 2, 50),
            vec![E::Snow],
            vec![L::Underground],
            Common,
        ),
        Enemy::new(
            151,
            "Lava Bat",
            160,
            16,
            Coins::new(0, 4, 0),
            vec![E::Any],
            vec![L::Underworld],
            Common,
        ),
        Enemy::new(
            152,
            "Giant Flying Fox",
            220,
            24,
            Coins::new(0, 4, 0),
            vec![E::Jungle, E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            153,
            "Giant Tortoise",
            470,
            30,
            Coins::new(0, 5, 0),
            vec![E::Jungle],
            vec![L::Surface, L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            154,
            "Ice Tortoise",
            400,
            28,
            Coins::new(0, 4, 50),
            vec![E::Snow],
            vec![L::Underground],
            Uncommon,
        ),
        Enemy::new(
            155,
            "Wolf",
            300,
            30,
            Coins::new(0, 10, 0),
            vec![E::Snow, E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            156,
            "Red Devil",
            600,
            40,
            Coins::new(0, 12, 0),
            vec![E::Any],
            vec![L::Underworld],
            Uncommon,
        ),
        Enemy::new(
            157,
            "Arapaima",
            200,
            30,
            Coins::new(0, 5, 0),
            vec![E::Jungle],
            vec![L::Surface, L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            159,
            "Vampire",
            750,
            24,
            Coins::new(0, 50, 0),
            vec![E::Day, E::Event],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            161,
            "Frozen Zombie",
            45,
            6,
            Coins::new(0, 0, 60),
            vec![E::Snow, E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            162,
            "Frankenstein",
            350,
            18,
            Coins::new(0, 6, 0),
            vec![E::Day, E::Event],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            163,
            "Black Recluse",
            350,
            40,
            Coins::new(0, 5, 0),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            164,
            "Wall Creeper",
            80,
            10,
            Coins::new(0, 1, 0),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            166,
            "Swamp Thing",
            450,
            26,
            Coins::new(0, 10, 0),
            vec![E::Day, E::Event],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            167,
            "Undead Viking",
            70,
            10,
            Coins::new(0, 2, 0),
            vec![E::Snow],
            vec![L::Underground],
            Common,
        ),
        Enemy::new(
            168,
            "Corrupt Penguin",
            70,
            4,
            Coins::new(0, 5, 0),
            vec![E::Snow, E::Night, E::Event],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            169,
            "Ice Elemental",
            200,
            20,
            Coins::new(0, 15, 0),
            vec![E::Snow, E::Night],
            vec![L::Surface, L::Underground],
            Common,
        ),
        Enemy::new(
            170,
            "Pigron (Corrupt)",
            210,
            16,
            Coins::new(0, 20, 0),
            vec![E::Snow, E::Corruption],
            vec![L::Underground],
            Uncommon,
        ),
        Enemy::new(
            171,
            "Pigron (Hallow)",
            210,
            16,
            Coins::new(0, 20, 0),
            vec![E::Snow, E::Hallow],
            vec![L::Underground],
            Uncommon,
        ),
        Enemy::new(
            172,
            "Rune Wizard",
            600,
            30,
            Coins::new(0, 50, 0),
            vec![E::Any],
            vec![L::Caverns],
            Rare,
        ),
        Enemy::new(
            173,
            "Crimera",
            40,
            8,
            Coins::new(0, 0, 90),
            vec![E::Crimson],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            174,
            "Herpling",
            220,
            26,
            Coins::new(0, 4, 50),
            vec![E::Crimson],
            vec![L::Surface, L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            175,
            "Angry Trapper",
            300,
            30,
            Coins::new(0, 6, 50),
            vec![E::Jungle],
            vec![L::Surface, L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            176,
            "Moss Hornet",
            220,
            22,
            Coins::new(0, 6, 0),
            vec![E::Jungle],
            vec![L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            177,
            "Derpling",
            300,
            26,
            Coins::new(0, 5, 0),
            vec![E::Jungle],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            179,
            "Crimson Axe",
            200,
            18,
            Coins::new(0, 10, 0),
            vec![E::Crimson],
            vec![L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            181,
            "Face Monster",
            70,
            10,
            Coins::new(0, 2, 0),
            vec![E::Crimson],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            182,
            "Floaty Gross",
            240,
            18,
            Coins::new(0, 5, 0),
            vec![E::Crimson],
            vec![L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            183,
            "Crimslime",
            200,
            26,
            Coins::new(0, 4, 0),
            vec![E::Crimson],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            184,
            "Spiked Ice Slime",
            60,
            8,
            Coins::new(0, 2, 0),
            vec![E::Snow],
            vec![L::Underground],
            Common,
        ),
        Enemy::new(
            185,
            "Snow Flinx",
            70,
            12,
            Coins::new(0, 2, 0),
            vec![E::Snow],
            vec![L::Underground],
            Uncommon,
        ),
        Enemy::new(
            195,
            "Nymph",
            300,
            16,
            Coins::new(2, 0, 0),
            vec![E::Any],
            vec![L::Caverns],
            Rare,
        ),
        Enemy::new(
            197,
            "Armored Viking",
            280,
            28,
            Coins::new(0, 5, 0),
            vec![E::Snow],
            vec![L::Underground],
            Uncommon,
        ),
        Enemy::new(
            198,
            "Lihzahrd",
            400,
            20,
            Coins::new(0, 6, 50),
            vec![E::Jungle],
            vec![L::Underground],
            Common,
        ),
        Enemy::new(
            201,
            "Skeleton",
            65,
            12,
            Coins::new(0, 1, 30),
            vec![E::Any],
            vec![L::Caverns],
            Common,
        ),
        Enemy::new(
            205,
            "Moth",
            1000,
            28,
            Coins::new(0, 6, 0),
            vec![E::Jungle],
            vec![L::Underground, L::Caverns],
            Rare,
        ),
        Enemy::new(
            206,
            "Icy Merman",
            280,
            30,
            Coins::new(0, 5, 0),
            vec![E::Snow],
            vec![L::Underground],
            Uncommon,
        ),
        Enemy::new(
            212,
            "Pirate Deckhand",
            300,
            17,
            Coins::new(0, 7, 0),
            vec![E::Event, E::Pirate],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            213,
            "Pirate Corsair",
            450,
            22,
            Coins::new(0, 10, 0),
            vec![E::Event, E::Pirate],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            214,
            "Pirate Deadeye",
            225,
            14,
            Coins::new(0, 10, 0),
            vec![E::Event, E::Pirate],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            215,
            "Pirate Crossbower",
            350,
            20,
            Coins::new(0, 15, 0),
            vec![E::Event, E::Pirate],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            216,
            "Pirate Captain",
            3000,
            30,
            Coins::new(5, 0, 0),
            vec![E::Event, E::Pirate],
            vec![L::Surface],
            Rare,
        ),
        Enemy::new(
            217,
            "Cochineal Beetle",
            40,
            10,
            Coins::new(0, 0, 60),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            218,
            "Cyan Beetle",
            40,
            10,
            Coins::new(0, 0, 60),
            vec![E::Snow],
            vec![L::Underground, L::Caverns],
            Rare,
        ),
        Enemy::new(
            219,
            "Lac Beetle",
            40,
            10,
            Coins::new(0, 0, 60),
            vec![E::Jungle],
            vec![L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            220,
            "Sea Snail",
            40,
            10,
            Coins::new(0, 0, 60),
            vec![E::Ocean],
            vec![L::Any],
            Rare,
        ),
        Enemy::new(
            221,
            "Squid",
            30,
            2,
            Coins::new(0, 1, 0),
            vec![E::Ocean],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            223,
            "Raincoat Zombie",
            50,
            8,
            Coins::new(0, 0, 70),
            vec![E::Rain, E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            224,
            "Flying Fish",
            20,
            4,
            Coins::new(0, 3, 0),
            vec![E::Rain],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            225,
            "Umbrella Slime",
            35,
            5,
            Coins::new(0, 2, 0),
            vec![E::Rain],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            226,
            "Flying Snake",
            260,
            28,
            Coins::new(0, 4, 0),
            vec![E::Jungle],
            vec![L::Underground],
            Common,
        ),
        Enemy::new(
            236,
            "Jungle Creeper",
            400,
            28,
            Coins::new(0, 10, 0),
            vec![E::Jungle],
            vec![L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            239,
            "Blood Crawler",
            60,
            8,
            Coins::new(0, 1, 30),
            vec![E::Crimson],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            241,
            "Blood Feeder",
            150,
            20,
            Coins::new(0, 5, 0),
            vec![E::Crimson],
            vec![L::Surface, L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            242,
            "Blood Jelly",
            150,
            20,
            Coins::new(0, 8, 0),
            vec![E::Crimson, E::Ocean],
            vec![L::Surface, L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            243,
            "Ice Golem",
            4000,
            32,
            Coins::new(1, 50, 0),
            vec![E::Snow, E::Rain],
            vec![L::Surface],
            Rare,
        ),
        Enemy::new(
            244,
            "Rainbow Slime",
            400,
            26,
            Coins::new(0, 20, 0),
            vec![E::Hallow, E::Rain],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            250,
            "Angry Nimbus",
            300,
            24,
            Coins::new(0, 3, 0),
            vec![E::Any, E::Rain],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            251,
            "Eyezor",
            1000,
            30,
            Coins::new(0, 50, 0),
            vec![E::Day, E::Event],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            252,
            "Parrot",
            100,
            12,
            Coins::new(0, 5, 0),
            vec![E::Event],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            253,
            "Reaper",
            700,
            22,
            Coins::new(0, 15, 0),
            vec![E::Day, E::Event],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            255,
            "Spore Zombie",
            220,
            16,
            Coins::new(0, 12, 0),
            vec![E::Mushroom],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            256,
            "Fungo Fish",
            140,
            20,
            Coins::new(0, 12, 0),
            vec![E::Mushroom],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            257,
            "Anomura Fungus",
            230,
            24,
            Coins::new(0, 13, 0),
            vec![E::Mushroom],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            258,
            "Mushi Ladybug",
            220,
            16,
            Coins::new(0, 15, 0),
            vec![E::Mushroom],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            258,
            "Fungi Bulb",
            90,
            4,
            Coins::new(0, 3, 50),
            vec![E::Mushroom],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            268,
            "Ichor Sticker",
            340,
            20,
            Coins::new(0, 4, 50),
            vec![E::Crimson],
            vec![L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            269,
            "Rusty Armored Bones",
            550,
            34,
            Coins::new(0, 10, 0),
            vec![E::Dungeon],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            273,
            "Blue Armored Bones",
            500,
            50,
            Coins::new(0, 10, 0),
            vec![E::Dungeon],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            277,
            "Hell Armored Bones",
            400,
            32,
            Coins::new(0, 10, 0),
            vec![E::Dungeon],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            282,
            "Ragged Caster",
            450,
            28,
            Coins::new(0, 15, 0),
            vec![E::Dungeon],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            283,
            "Necromancer",
            450,
            24,
            Coins::new(0, 15, 0),
            vec![E::Dungeon],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            285,
            "Diabolist",
            250,
            10,
            Coins::new(0, 15, 0),
            vec![E::Dungeon],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            287,
            "Bone Lee",
            1000,
            42,
            Coins::new(0, 20, 0),
            vec![E::Dungeon],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            288,
            "Dungeon Spirit",
            200,
            30,
            Coins::new(0, 5, 0),
            vec![E::Dungeon],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            289,
            "Giant Cursed Skull",
            400,
            20,
            Coins::new(0, 1, 50),
            vec![E::Dungeon],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            290,
            "Paladin",
            5000,
            50,
            Coins::new(5, 0, 0),
            vec![E::Dungeon],
            vec![L::Any],
            Rare,
        ),
        Enemy::new(
            291,
            "Skeleton Sniper",
            400,
            28,
            Coins::new(0, 10, 0),
            vec![E::Dungeon],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            292,
            "Tactical Skeleton",
            400,
            28,
            Coins::new(0, 10, 0),
            vec![E::Dungeon],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            293,
            "Skeleton Commando",
            400,
            28,
            Coins::new(0, 10, 0),
            vec![E::Dungeon],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            298,
            "Cardinal",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Forest, E::Snow, E::Hallow],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            299,
            "Squirrel",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Forest],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            300,
            "Mouse",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            301,
            "Raven",
            35,
            2,
            Coins::new(0, 0, 50),
            vec![E::Graveyard],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            304,
            "Hoppin' Jack",
            175,
            20,
            Coins::new(0, 5, 0),
            vec![E::Forest, E::Night, E::Graveyard],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            305,
            "Scarecrow",
            500,
            18,
            Coins::new(0, 12, 0),
            vec![E::Night, E::Event, E::Pumpkin],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            315,
            "Headless Horseman",
            5000,
            40,
            Coins::new(1, 0, 0),
            vec![E::Night, E::Pumpkin, E::Event],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            316,
            "Ghost",
            50,
            4,
            Coins::new(0, 0, 90),
            vec![E::Graveyard],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            325,
            "Mourning Wood",
            14000,
            34,
            Coins::new(1, 0, 0),
            vec![E::Event, E::Night, E::Pumpkin],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            327,
            "Pumpking",
            26000,
            40,
            Coins::new(5, 0, 0),
            vec![E::Event, E::Night, E::Pumpkin],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            326,
            "Splinterling",
            1200,
            32,
            Coins::new(0, 20, 0),
            vec![E::Night, E::Event, E::Pumpkin],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            329,
            "Hellhound",
            1800,
            38,
            Coins::new(0, 30, 0),
            vec![E::Night, E::Event, E::Pumpkin],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            330,
            "Poltergeist",
            1250,
            44,
            Coins::new(0, 45, 0),
            vec![E::Night, E::Event, E::Pumpkin],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            338,
            "Zombie Elf",
            600,
            18,
            Coins::new(0, 12, 0),
            vec![E::Night, E::Event, E::Frost],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            342,
            "Gingerbread Man",
            750,
            26,
            Coins::new(0, 18, 0),
            vec![E::Night, E::Event, E::Frost],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            343,
            "Yeti",
            3500,
            50,
            Coins::new(0, 30, 0),
            vec![E::Night, E::Event, E::Frost],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            344,
            "Everscream",
            13000,
            38,
            Coins::new(1, 0, 0),
            vec![E::Event, E::Night, E::Frost],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            345,
            "Ice Queen",
            34000,
            38,
            Coins::new(5, 0, 0),
            vec![E::Event, E::Night, E::Frost],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            346,
            "Santa-NK1",
            18000,
            56,
            Coins::new(1, 0, 0),
            vec![E::Event, E::Night, E::Frost],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            347,
            "Elf Copter",
            1200,
            28,
            Coins::new(0, 10, 0),
            vec![E::Night, E::Event, E::Frost],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            348,
            "Nutcracker",
            1800,
            26,
            Coins::new(0, 15, 0),
            vec![E::Night, E::Event, E::Frost],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            350,
            "Elf Archer",
            900,
            30,
            Coins::new(0, 9, 0),
            vec![E::Night, E::Event, E::Frost],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            351,
            "Krampus",
            2500,
            40,
            Coins::new(0, 30, 0),
            vec![E::Night, E::Event, E::Frost],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            352,
            "Flocko",
            450,
            8,
            Coins::new(0, 5, 0),
            vec![E::Event, E::Night, E::Frost],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            355,
            "Firefly",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Forest, E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            356,
            "Butterfly",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Forest],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            357,
            "Worm",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            358,
            "Lightning Bug",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Hallow, E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            359,
            "Snail",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Rare,
        ),
        Enemy::new(
            360,
            "Glowing Snail",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Mushroom],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            361,
            "Frog",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Jungle],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            362,
            "Duck",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            366,
            "Scorpion",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Desert],
            vec![L::Surface, L::Underground],
            Common,
        ),
        Enemy::new(
            375,
            "Truffle Worm",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Mushroom],
            vec![L::Any],
            Rare,
        ),
        Enemy::new(
            377,
            "Grasshopper",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Forest],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            379,
            "Cultist Archer",
            200,
            14,
            Coins::new(0, 10, 0),
            vec![E::Dungeon],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            381,
            "Brain Scrambler",
            350,
            25,
            Coins::new(0, 10, 0),
            vec![E::Event, E::Martian],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            382,
            "Ray Gunner",
            350,
            25,
            Coins::new(0, 10, 0),
            vec![E::Event, E::Martian],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            383,
            "Martian Officer",
            300,
            50,
            Coins::new(0, 12, 0),
            vec![E::Event, E::Martian],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            385,
            "Gray Grunt",
            750,
            30,
            Coins::new(0, 6, 0),
            vec![E::Event, E::Martian],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            368,
            "Martian Engineer",
            400,
            34,
            Coins::new(0, 12, 0),
            vec![E::Event, E::Martian],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            388,
            "Martian Drone",
            300,
            16,
            Coins::new(0, 10, 0),
            vec![E::Event, E::Martian],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            389,
            "Gigazapper",
            600,
            16,
            Coins::new(0, 12, 0),
            vec![E::Event, E::Martian],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            391,
            "Scutlix",
            600,
            30,
            Coins::new(0, 12, 0),
            vec![E::Event, E::Martian],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            392,
            "Martian Saucer",
            17000,
            100,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Martian],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            399,
            "Martian Probe",
            500,
            5,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Space, L::Surface],
            Rare,
        ),
        Enemy::new(
            402,
            "Milkyway Weaver",
            1200,
            0,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Stardust],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            405,
            "Star Cell",
            300,
            50,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Stardust],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            407,
            "Flow Invader",
            1500,
            38,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Stardust],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            409,
            "Twinkle Popper",
            800,
            40,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Stardust],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            411,
            "Stargazer",
            700,
            34,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Stardust],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            412,
            "Crawltipede",
            10000,
            0,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Solar],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            415,
            "Drakomire",
            800,
            32,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Solar],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            417,
            "Sroller",
            700,
            34,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Solar],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            418,
            "Corite",
            600,
            26,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Solar],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            419,
            "Selenian",
            800,
            30,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Solar],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            420,
            "Nebula Floater",
            1300,
            20,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Nebula],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            421,
            "Brain Suckler",
            330,
            34,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Nebula],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            423,
            "Evolution Beast",
            850,
            46,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Nebula],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            424,
            "Predictor",
            700,
            30,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Nebula],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            425,
            "Storm Diver",
            800,
            40,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Vortex],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            426,
            "Alien Queen",
            1000,
            44,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Vortex],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            429,
            "Vortexian",
            700,
            34,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Lunar, E::Vortex],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            438,
            "Lunatic Devotee",
            400,
            0,
            Coins::new(0, 0, 0),
            vec![E::Dungeon],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            453,
            "Skeleton Merchant",
            250,
            30,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Caverns],
            Rare,
        ),
        Enemy::new(
            454,
            "Phantasm Dragon",
            10000,
            30,
            Coins::new(0, 0, 0),
            vec![E::Dungeon],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            460,
            "Butcher",
            700,
            30,
            Coins::new(0, 10, 0),
            vec![E::Event, E::Day, E::Eclipse],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            461,
            "Creature from the Deep",
            400,
            22,
            Coins::new(0, 10, 0),
            vec![E::Event, E::Day, E::Eclipse],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            462,
            "Fritz",
            270,
            14,
            Coins::new(0, 6, 0),
            vec![E::Event, E::Day, E::Eclipse],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            463,
            "Nailhead",
            4000,
            34,
            Coins::new(0, 30, 0),
            vec![E::Event, E::Day, E::Eclipse],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            464,
            "Vicious Bunny",
            75,
            5,
            Coins::new(0, 5, 0),
            vec![E::Event, E::Blood, E::Night],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            465,
            "Vicious Goldfish",
            110,
            7,
            Coins::new(0, 5, 0),
            vec![E::Event, E::Crimson, E::Blood, E::Night],
            vec![L::Surface, L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            466,
            "Psycho",
            550,
            40,
            Coins::new(0, 15, 0),
            vec![E::Event, E::Day, E::Eclipse],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            467,
            "Deadly Sphere",
            350,
            80,
            Coins::new(0, 9, 0),
            vec![E::Event, E::Day, E::Eclipse],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            468,
            "Dr. Man Fly",
            500,
            24,
            Coins::new(0, 13, 0),
            vec![E::Event, E::Day, E::Eclipse],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            469,
            "The Possessed",
            600,
            28,
            Coins::new(0, 13, 0),
            vec![E::Event, E::Day, E::Eclipse],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            470,
            "Vicious Penguin",
            75,
            5,
            Coins::new(0, 5, 0),
            vec![E::Event, E::Blood, E::Snow, E::Night],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            471,
            "Goblin Warlock",
            2000,
            26,
            Coins::new(0, 50, 0),
            vec![E::Event, E::Goblin],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            472,
            "Shadowflame Apparition",
            180,
            18,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Goblin],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            473,
            "Corrupt Mimic",
            3500,
            34,
            Coins::new(3, 0, 0),
            vec![E::Corruption],
            vec![L::Underground, L::Caverns],
            Rare,
        ),
        Enemy::new(
            474,
            "Crimson Mimic",
            3500,
            34,
            Coins::new(3, 0, 0),
            vec![E::Crimson],
            vec![L::Underground, L::Caverns],
            Rare,
        ),
        Enemy::new(
            475,
            "Hallowed Mimic",
            3500,
            34,
            Coins::new(3, 0, 0),
            vec![E::Hallow],
            vec![L::Underground, L::Caverns],
            Rare,
        ),
        Enemy::new(
            477,
            "Mothron",
            6000,
            30,
            Coins::new(5, 0, 0),
            vec![E::Event, E::Day, E::Eclipse],
            vec![L::Surface],
            Rare,
        ),
        Enemy::new(
            479,
            "Baby Mothron",
            700,
            14,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Day, E::Eclipse],
            vec![L::Surface],
            Rare,
        ),
        Enemy::new(
            480,
            "Medusa",
            400,
            20,
            Coins::new(0, 10, 0),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Rare,
        ),
        Enemy::new(
            481,
            "Hoplite",
            70,
            10,
            Coins::new(0, 3, 0),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            482,
            "Granite Golem",
            110,
            18,
            Coins::new(0, 5, 0),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            483,
            "Granite Elemental",
            40,
            8,
            Coins::new(0, 10, 0),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            484,
            "Enchanted Nightcrawler",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any, E::Night],
            vec![L::Surface],
            Rare,
        ),
        Enemy::new(
            485,
            "Grubby",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Jungle],
            vec![L::Surface, L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            486,
            "Sluggy",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Jungle],
            vec![L::Surface, L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            487,
            "Buggy",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Jungle],
            vec![L::Surface, L::Underground, L::Caverns],
            Uncommon,
        ),
        Enemy::new(
            489,
            "Blood Zombie",
            75,
            8,
            Coins::new(0, 1, 50),
            vec![E::Event, E::Blood, E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            490,
            "Drippler",
            50,
            14,
            Coins::new(0, 1, 50),
            vec![E::Event, E::Blood, E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            491,
            "Flying Dutchman",
            8000,
            20,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Pirate],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            494,
            "Crawdad",
            50,
            6,
            Coins::new(0, 1, 20),
            vec![E::Any],
            vec![L::Caverns],
            Common,
        ),
        Enemy::new(
            496,
            "Giant Shelly",
            50,
            12,
            Coins::new(0, 1, 20),
            vec![E::Any],
            vec![L::Caverns],
            Common,
        ),
        Enemy::new(
            498,
            "Salamander (Any)",
            65,
            10,
            Coins::new(0, 1, 20),
            vec![E::Any],
            vec![L::Caverns],
            Common,
        ),
        Enemy::new(
            510,
            "Dune Splicer",
            500,
            34,
            Coins::new(0, 7, 0),
            vec![E::Desert],
            vec![L::Surface, L::Underground],
            Uncommon,
        ),
        Enemy::new(
            520,
            "Martian Walker",
            2000,
            40,
            Coins::new(0, 0, 0),
            vec![E::Event, E::Martian],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            524,
            "Ghoul",
            180,
            26,
            Coins::new(0, 5, 0),
            vec![E::Desert],
            vec![L::Underground],
            Common,
        ),
        Enemy::new(
            525,
            "Vile Ghoul",
            250,
            30,
            Coins::new(0, 6, 50),
            vec![E::Desert, E::Corruption],
            vec![L::Underground],
            Common,
        ),
        Enemy::new(
            526,
            "Tainted Ghoul",
            220,
            32,
            Coins::new(0, 6, 50),
            vec![E::Desert, E::Crimson],
            vec![L::Underground],
            Common,
        ),
        Enemy::new(
            527,
            "Dreamer Ghoul",
            300,
            32,
            Coins::new(0, 7, 50),
            vec![E::Desert, E::Hallow],
            vec![L::Underground],
            Common,
        ),
        Enemy::new(
            528,
            "Lamia (Any)",
            350,
            28,
            Coins::new(0, 6, 0),
            vec![E::Desert, E::Hallow],
            vec![L::Underground],
            Common,
        ),
        Enemy::new(
            530,
            "Sand Poacher",
            320,
            24,
            Coins::new(0, 6, 0),
            vec![E::Desert],
            vec![L::Underground],
            Common,
        ),
        Enemy::new(
            532,
            "Basilisk",
            270,
            34,
            Coins::new(0, 8, 0),
            vec![E::Desert],
            vec![L::Underground],
            Uncommon,
        ),
        Enemy::new(
            533,
            "Desert Spirit",
            220,
            20,
            Coins::new(0, 12, 0),
            vec![E::Desert, E::Crimson, E::Corruption],
            vec![L::Underground],
            Uncommon,
        ),
        Enemy::new(
            534,
            "Tortured Soul",
            400,
            20,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Underworld],
            Uncommon,
        ),
        Enemy::new(
            536,
            "The Bride",
            200,
            8,
            Coins::new(0, 10, 0),
            vec![E::Event, E::Blood, E::Graveyard],
            vec![L::Surface],
            Rare,
        ),
        Enemy::new(
            537,
            "Sand Slime",
            50,
            5,
            Coins::new(0, 0, 75),
            vec![E::Desert],
            vec![L::Underground],
            Common,
        ),
        Enemy::new(
            541,
            "Sand Elemental",
            5000,
            30,
            Coins::new(1, 50, 0),
            vec![E::Desert],
            vec![L::Surface],
            Rare,
        ),
        Enemy::new(
            542,
            "Sand Shark",
            360,
            20,
            Coins::new(0, 4, 0),
            vec![E::Desert],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            543,
            "Bone Biter",
            380,
            24,
            Coins::new(0, 4, 0),
            vec![E::Desert, E::Corruption],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            544,
            "Flesh Reaver",
            400,
            22,
            Coins::new(0, 4, 0),
            vec![E::Desert, E::Crimson],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            545,
            "Crystal Thresher",
            450,
            26,
            Coins::new(0, 4, 0),
            vec![E::Desert, E::Hallow],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            546,
            "Angry Tumbler",
            50,
            6,
            Coins::new(0, 1, 0),
            vec![E::Desert],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            551,
            "Betsy",
            50000,
            38,
            Coins::new(0, 0, 0),
            vec![E::Event, E::OldOnes],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            552,
            "Etherian Goblin",
            30,
            14,
            Coins::new(0, 0, 0),
            vec![E::Event, E::OldOnes],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            553,
            "Etherian Goblin Bomber",
            50,
            16,
            Coins::new(0, 0, 0),
            vec![E::Event, E::OldOnes],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            558,
            "Etherian Wyvern",
            60,
            4,
            Coins::new(0, 0, 0),
            vec![E::Event, E::OldOnes],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            561,
            "Etherian Javelin Thrower",
            60,
            18,
            Coins::new(0, 0, 0),
            vec![E::Event, E::OldOnes],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            564,
            "Dark Mage",
            4000,
            38,
            Coins::new(0, 0, 0),
            vec![E::Event, E::OldOnes],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            568,
            "Wither Beast",
            500,
            30,
            Coins::new(0, 0, 0),
            vec![E::Event, E::OldOnes],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            570,
            "Drakin",
            900,
            30,
            Coins::new(0, 0, 0),
            vec![E::Event, E::OldOnes],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            572,
            "Kobold",
            260,
            26,
            Coins::new(0, 0, 0),
            vec![E::Event, E::OldOnes],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            574,
            "Kobold Glider",
            170,
            16,
            Coins::new(0, 0, 0),
            vec![E::Event, E::OldOnes],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            576,
            "Ogre",
            13000,
            40,
            Coins::new(0, 0, 0),
            vec![E::Event, E::OldOnes],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            578,
            "Etherian Lightning Bug",
            500,
            36,
            Coins::new(0, 0, 0),
            vec![E::Event, E::OldOnes],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            580,
            "Antlion Charger",
            80,
            10,
            Coins::new(0, 0, 80),
            vec![E::Desert],
            vec![L::Surface, L::Underground],
            Common,
        ),
        Enemy::new(
            581,
            "Antlion Swarmer",
            60,
            8,
            Coins::new(0, 0, 90),
            vec![E::Desert],
            vec![L::Surface, L::Underground],
            Common,
        ),
        Enemy::new(
            583,
            "Fairy (Any)",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any, E::Night],
            vec![L::Surface, L::Underground, L::Caverns],
            Rare,
        ),
        Enemy::new(
            586,
            "Zombie Merman",
            400,
            20,
            Coins::new(0, 10, 0),
            vec![E::Event, E::Blood, E::Night, E::Ocean],
            vec![L::Any],
            Rare,
        ),
        Enemy::new(
            587,
            "Wandering Eye Fish",
            300,
            18,
            Coins::new(0, 10, 0),
            vec![E::Event, E::Blood, E::Night, E::Ocean],
            vec![L::Any],
            Rare,
        ),
        Enemy::new(
            602,
            "Seagull",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Day, E::Ocean],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            604,
            "Ladybug",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            606,
            "Maggot",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Graveyard],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            610,
            "Rat",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Graveyard],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            611,
            "Owl",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Forest, E::Night],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            615,
            "Dolphin",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Ocean],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            616,
            "Turtle",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Forest, E::Day],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            617,
            "Jungle Turtle",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Jungle],
            vec![L::Surface],
            Common,
        ),
        Enemy::new(
            620,
            "Hemogoblin Shark",
            5000,
            30,
            Coins::new(0, 75, 0),
            vec![E::Event, E::Blood, E::Night, E::Ocean],
            vec![L::Any],
            Rare,
        ),
        Enemy::new(
            621,
            "Blood Eel",
            6000,
            30,
            Coins::new(0, 75, 0),
            vec![E::Event, E::Blood, E::Night, E::Ocean],
            vec![L::Any],
            Rare,
        ),
        Enemy::new(
            624,
            "Gnome",
            25,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            625,
            "Sea Turtle",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Ocean],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            626,
            "Seahorse",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Ocean],
            vec![L::Any],
            Uncommon,
        ),
        Enemy::new(
            628,
            "Angry Dandelion",
            50,
            0,
            Coins::new(0, 0, 50),
            vec![E::Forest],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            630,
            "Blood Mummy",
            180,
            18,
            Coins::new(0, 7, 0),
            vec![E::Desert, E::Crimson],
            vec![L::Surface, L::Underground, L::Caverns],
            Common,
        ),
        Enemy::new(
            631,
            "Rock Golem",
            1000,
            35,
            Coins::new(2, 50, 0),
            vec![E::Any],
            vec![L::Caverns],
            Rare,
        ),
        Enemy::new(
            634,
            "Spore Bat",
            16,
            2,
            Coins::new(0, 0, 90),
            vec![E::Mushroom],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            635,
            "Spore Skeleton",
            60,
            8,
            Coins::new(0, 1, 0),
            vec![E::Mushroom],
            vec![L::Any],
            Common,
        ),
        Enemy::new(
            639,
            "Gem Squirrel (Any)",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Caverns],
            Rare,
        ),
        Enemy::new(
            646,
            "Gem Bunny (Any)",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Caverns],
            Rare,
        ),
        Enemy::new(
            653,
            "Hell Butterfly",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Underworld],
            Uncommon,
        ),
        Enemy::new(
            654,
            "Lavafly",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Underworld],
            Uncommon,
        ),
        Enemy::new(
            655,
            "Magma Snail",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Underworld],
            Uncommon,
        ),
        Enemy::new(
            661,
            "Prismatic Lacewing",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Hallow, E::Night],
            vec![L::Surface],
            Rare,
        ),
        Enemy::new(
            669,
            "Stinkbug",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Forest],
            vec![L::Surface],
            Uncommon,
        ),
        Enemy::new(
            676,
            "Shimmer Slime",
            80,
            5,
            Coins::new(0, 1, 50),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Rare,
        ),
        Enemy::new(
            677,
            "Faeling",
            5,
            0,
            Coins::new(0, 0, 0),
            vec![E::Any],
            vec![L::Underground, L::Caverns],
            Rare,
        ),
        Enemy::new(
            1004,
            "Pinky",
            150,
            5,
            Coins::new(1, 0, 0),
            vec![E::Any],
            vec![L::Surface, L::Underground, L::Caverns],
            Rare,
        ),
    ])
}
